a = float(input("შეიყვანე პირველი რიცხვი (float): "))
b = int(input("შეიყვანე მეორე რიცხვი (int): "))

print("ჯამი:", a + b)
print("სხვაობა:", a - b)
print("ნამრავლი:", a * b)
print("გაყოფა:", a / b)
print("მთელი გაყოფა:", a // b)
print("ხარისხი:", a ** b)
print("ნაშთი:", a % b)
